Add no task/running/queued information to Uses
NUbots/NUbots pull request #1032
Opened 2023-03-05 05:44 UTC by ysims

This PR adds in information so a provider can find out if its task is already running or queued or not sent yet.

Pretty good for planners, since we don't want to go requesting a skill again when we already just requested it! ie Kick and Get Up planners.

Stops us having to keep track in the reactor if the kick or get up has already been requested.

Should add this to NUbots/NUbook#122.

2023-03-05 05:45 UTC, ysims commented on module/extension/Director/tests/uses_state.cpp
> + * Copyright 2022 NUbots <nubots@nubots.net>
```suggestion
 * Copyright 2023 NUbots <nubots@nubots.net>
```

2023-03-05 11:42 UTC, TrentHouliston requested changes
Looks pretty good, just a few things to cleanup, and a little more breadth in the root task unit test

2023-03-05 11:42 UTC, TrentHouliston commented on module/extension/Director/tests/uses_state_root.cpp
> +                });
To really test the root provider stuff properly, split this into 3x reactions triggered on separate messages

One that emits the task
One that emits the nullptr
And one that just reads the uses state

That way you can check that multiple different non provider reactions all behave as if they are a single "root" provider

2023-03-05 11:42 UTC, TrentHouliston commented on module/extension/Director/src/information/get_group_info.cpp
> +            if (groups.at(type).active_task != nullptr) {
Pull the groups.at(type) out into a `auto& group =` since you use it a few times here

2023-03-05 11:42 UTC, TrentHouliston commented on module/extension/Director/src/information/get_group_info.cpp
> +            if (providers.contains(r_id)) {
You know this is true from your earlier checks, you can probably make a `auto&` for it right after the root_type stuff

2023-03-11 03:42 UTC, TrentHouliston approved these changes

2023-03-11 04:09 UTC, merged