Add ability to make requests to OpenAI api
NUbots/NUbots pull request #1258
Opened 2023-10-19 10:48 UTC by Tom0Brien

This PR adds a module that integrates with OpenAI's api to send text prompts and receive generated responses. Additionally, the responses can be "spoken" using the "Say" skill. I am not sure whether or not it makes sense to integrate this within the Director system or not.

2023-10-25 23:45 UTC, ysims reviewed
Same comment about the tester here from the speech PR
The GPT module can have a test config value to use for simpler testing. 
A role with just Say and GPT wuld be useful. then leave `behaviour.role` for soccer behaviour testing.

2023-10-25 23:45 UTC, ysims commented on module/skill/GPT/README.md
> +- `message::skill::GPTResponse`: A response from GPT containing the generated text based on the input request.
```suggestion
- `message::skill::Say`: A Task requesting to speak using the output of the GPT model based on the input request.
```

2023-11-24 12:16 UTC, jpptm requested changes
Nitpicking

2023-11-24 12:16 UTC, jpptm commented on module/skill/GPT/data/config/GPT.yaml
> +openai_api_key: ""
```suggestion
# The OpenAI API costs $$$ to use, so we need to use a key to access it. This must be filled before compiling. DO NOT COMMIT THE KEY IN THE REPOSITORY.
openai_api_key: ""
```

2023-11-24 12:16 UTC, jpptm commented on module/skill/GPT/src/GPT.cpp
> +                    {"temperature", 0}};
Should these be configurable values?

2023-11-26 11:01 UTC, Tom0Brien commented on module/skill/GPT/src/GPT.cpp
> +                    {"temperature", 0}};
Yes, good point.

2024-03-31 08:03 UTC, closed without merging