Brattan/head in ready beh 34
NUbots/NUbots pull request #1335
Opened 2024-04-22 12:22 UTC by AnExParrot

Things the PR does go here

- Makes the robot look forward during initial
### Pre-PR Checklist:

Have you

- [ ] Updated NUbook if necessary (add link to NUbook PR here)
- [ ] Added/updated tests for your changes, including regression tests for bug fixes
- [ ] Updated relevant module READMEs
- [ ] Added/modified [documentation directives](https://nubook.nubots.net/guides/general/code-conventions#documentation) in relevant code
- [ ] Added a descriptive title and relevant labels to the PR

2024-04-22 15:02 UTC, Tom0Brien requested changes

2024-04-22 15:03 UTC, Tom0Brien commented on module/purpose/Defender/src/Defender.cpp
> +            Eigen::Vector3d uPCt =
Add the emit to the ready start as well, just incase `INITIAL` never runs

2024-04-22 21:45 UTC, ysims commented
Title of the PR needs changing, see https://nubook.nubots.net/guides/general/git#making-a-pull-request

2024-04-22 21:49 UTC, ysims commented on module/purpose/Defender/src/Defender.cpp
> +            emit<Task>(std::make_unique<Look>(uPCt, true));
going on from [Tom's comment ](https://github.com/NUbots/NUbots/pull/1335/files#r1574917410)
```suggestion
            emit<Task>(std::make_unique<Look>(Eigen::Vector3d::UnitX(), true));
```

2024-05-03 05:10 UTC, Tom0Brien approved these changes

2024-05-03 06:09 UTC, merged