Penalty States
NUbots/NUbots pull request #1480
Opened 2024-08-24 02:03 UTC by JesseWilliamson

## In this PR:

All game states:
- If in sub mode 1 (freeze/ball repositioning by referee) all robots stand still

Direct Free kick, indirect free kick, throw in, corner kick:
- If it's our turn to play, all robots play as normal.
- If it's the opposing team's turn to play, all robots stand still and watch the ball except goalie which plays as normal.

Goal Kick:
- Same as direct free kick. Bounding boxes will cause goalie to take the kick if possible.

Penalty Kick:
- If the opposing team is given a penalty kick, striker and defender will walk to a configured defence position (or the edge of their bounding box if it lies outside this region). At this location all robots stand still and goalie dives to ball if it approaches.
- If our team is given a penalty kick all robots play as normal.

## Problems and possible improvements:

Positioning and sub modes
- Once the penalty state is called, robots are given time to position themselves before the ball is kicked. We aren't doing this and we should be. It's not clear to me from the rules and GameController wiki exactly how this is supposed to work.

Moving away from the ball
- Robots are supposed to stay 0.75m away from the ball if the opposing team is taking a direct free kick, indirect free kick, goal kick, corner kick, or throw in. We should implement behaviour for moving away from the ball and into a valid, favourable position when the other team is taking a kick. Just not in this PR.

## More information:

Robocup Rules: http://humanoid.robocup.org/wp-content/uploads/RC-HL-2024-Rules.pdf
GameController: https://github.com/RoboCup-Humanoid-TC/GameController
Information on game sub mode: https://github.com/RoboCup-Humanoid-TC/GameController/wiki/SecondaryStateInfo

2024-08-24 02:24 UTC, ysims commented on module/purpose/Goalie/src/Goalie.cpp
> +                    emit<Task>(std::make_unique<DiveToBall>(), 4);
maybe change this to the normal playing strategy, I don't think we wanted to dive anymore

2024-09-09 03:31 UTC, Tom0Brien commented on module/purpose/Defender/src/Defender.cpp
> +                if ((int) game_state.data.secondary_state.team_performing != (int) game_state.data.team.team_id) {
Is there a reason for these (int) casts?

2025-01-08 00:04 UTC, c3440776 commented
Hey @JesseWilliamson, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #1480 (lowkey idk if i slayed but hopefully yas)**](https://gitkraken.dev/drafts/81a41779-25ba-4f7d-b26c-1ae97ae9b243?source=PRComment)
>https://github.com/NUbots/NUbots/pull/1480

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/81a41779-25ba-4f7d-b26c-1ae97ae9b243?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPQVd0TW5NNTVURjFLIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

2025-01-08 02:33 UTC, JohanneMontano requested changes
Theres a bit of duplicated code as well. It may be possible to condense all of these into one module to make reading easier, but maybe in another pr.

2025-01-08 02:33 UTC, JohanneMontano commented on module/purpose/Goalie/src/Goalie.cpp
> +                if (int(game_state.data.secondary_state.team_performing) != int(game_state.data.team.team_id)) {
From here onwards, I think we should remove the int casts cause they should not be needed

2025-01-08 21:46 UTC, ysims commented on module/purpose/Defender/src/Defender.hpp
> +            Eigen::Vector3f penalty_defence_position = Eigen::Vector3f::Zero();
change this to a double and then you don't need to do all the casting 

```suggestion
            Eigen::Vector3d penalty_defence_position = Eigen::Vector3f::Zero();
```

2025-01-09 20:52 UTC, nmthais commented on module/purpose/Defender/src/Defender.hpp
> +            Eigen::Vector3f penalty_defence_position = Eigen::Vector3f::Zero();
omg thanks girl

2025-01-10 05:04 UTC, ysims approved these changes

2025-01-13 02:02 UTC, JohanneMontano approved these changes

2025-01-13 22:11 UTC, merged