Speeds up stand up front and back scripts
NUbots/NUbots pull request #1484
Opened 2024-09-07 01:13 UTC by Crafty15

This was tested on Kevin but may work on the others.

2024-11-07 05:56 UTC, Tom0Brien requested changes
Fix formatting

2025-01-13 22:37 UTC, Tom0Brien submitted a review, later dismissed
Lgtm, may be worth checking if this works across robots and just having a single script

2025-04-03 00:23 UTC, ysims approved these changes

2025-04-03 12:23 UTC, Tom0Brien submitted a review, later dismissed

2025-04-05 09:17 UTC, ysims approved these changes

2025-04-05 09:23 UTC, merged