[NUsight] Initial setup for Kinematics tab
NUbots/NUbots pull request #1516
Opened 2024-12-13 22:54 UTC by KimKhangHoang

This PR implements the basic setup for the Kinematics tab based mostly on the structure of the Localisation tab.

2025-04-08 02:15 UTC, ysims reviewed
Nice!
CI will fail until #1546 is merged, once that's in you can merge main and this should hopefully pass.

2025-04-08 02:15 UTC, ysims commented on nusight2/src/client/components/localisation/r3f_components/text_geometry_helper/tmp7qhfputt/TextGeometryHelper.tsx
> +};
this looks like a temp file generated from the formatting tool

2025-04-08 02:15 UTC, ysims commented on nusight2/src/assets/fonts/roboto/tmpajzd1jaw/Roboto Medium_Regular.json
> +{
this looks like a temp file generated from the formatting tool

2025-04-08 02:15 UTC, ysims commented on nusight2/src/client/components/kinematics/r3f_components/coordinates/view.tsx
> +    loader.load("/fonts/roboto/Roboto Medium_Regular.json", (font: any) => {
can we change this filename so the space is an underscore?

2025-04-09 23:57 UTC, KimKhangHoang commented on nusight2/src/client/components/localisation/r3f_components/text_geometry_helper/tmp7qhfputt/TextGeometryHelper.tsx
> +};
oh yeah, I'll delete it

2025-04-09 23:59 UTC, KimKhangHoang commented on nusight2/src/client/components/kinematics/r3f_components/coordinates/view.tsx
> +    loader.load("/fonts/roboto/Roboto Medium_Regular.json", (font: any) => {
Sure, I'll rename it to Roboto_Medium_Regular.json

2025-04-20 08:44 UTC, ysims commented
@Tom0Brien can you check if this is what you're after in terms of functionality? I think there was talk of showing axis on all the joints, but doing that in a way to prevent clutter might be tricky and could be another PR.

2025-04-20 10:17 UTC, Tom0Brien requested changes
small thing, then LGTM!

2025-04-20 10:17 UTC, Tom0Brien commented on nusight2/src/client/components/kinematics/r3f_components/nugus/view.tsx
> +    if (robotRef.current) {
I don't think we should have the robot orientation changing, just keep the pose fixed and update joints

2025-04-22 05:43 UTC, KimKhangHoang commented on nusight2/src/client/components/kinematics/r3f_components/nugus/view.tsx
> +    if (robotRef.current) {
Thanks, Tom — I’ve removed the line that updated the robot’s quaternion.

I also noticed that some joints (like hip yaw or ankle roll) have static values (always 0 or fixed), at least in the sample data I’m running. I’ve kept them in for now. Would it make sense to treat these as redundant and remove them from the rendering and UI display, or do they have semantic meaning in other contexts?

2025-04-22 09:12 UTC, JosephusPaye reviewed
Nice work 👍 

Just two suggestions...

2025-04-22 09:12 UTC, JosephusPaye commented on nusight2/src/client/components/kinematics/r3f_components/axes/view.tsx
For these `r3f_components/XYZ/view.tsx` files, you can simplify by just having `r3f_components/XYZ.tsx`, instead of having each in its own folder with just the one file.

Generally speaking, the separation into model/view/controller is something we want to keep only at the page/tab-level going forward. Plain React components can be stored in a file named after them, without extra folders if not necessary.

2025-04-22 09:12 UTC, JosephusPaye commented on nusight2/src/client/components/localisation/r3f_components/text_geometry_helper/TextGeometryHelper.tsx
Related to my other comment, this can be moved up on level to be `r3f_components/text_geometry_helper.tsx` (file names should be in camel case, even ones with components).

2025-04-23 04:09 UTC, KimKhangHoang commented on nusight2/src/client/components/kinematics/r3f_components/axes/view.tsx
Thanks, Josephus — I’ve flattened the R3F components under the kinematics tab and renamed the files to camelCase as suggested.

2025-04-23 04:09 UTC, KimKhangHoang commented on nusight2/src/client/components/localisation/r3f_components/text_geometry_helper/TextGeometryHelper.tsx
I noticed other parts of the codebase with similar one-file-per-folder setups or non-camelCase names. I’ve left those as-is to keep this PR focused, but it might be something worth cleaning up in a separate PR down the line.

2025-04-23 07:55 UTC, Tom0Brien commented on nusight2/src/client/components/kinematics/r3f_components/nugus/view.tsx
> +    if (robotRef.current) {
They should definitely be kept.

2025-04-23 07:58 UTC, Tom0Brien approved these changes
LGTM!

2025-04-23 08:00 UTC, Tom0Brien commented on nusight2/src/client/components/localisation/r3f_components/text_geometry_helper/TextGeometryHelper.tsx
Good point. The localisation view has these unneeded folders, should clean that up.

2025-04-23 14:00 UTC, JosephusPaye commented on nusight2/src/client/components/localisation/r3f_components/text_geometry_helper/TextGeometryHelper.tsx
Oh damn, I meant snake case 😅

2025-04-24 04:29 UTC, KimKhangHoang commented
I’ve updated the file names to snake_case and kinda cleaned up R3F components (since I think it was a quick fix), as well as merged with the latest changes from main.

2025-04-24 04:37 UTC, ysims approved these changes

2025-04-24 05:00 UTC, merged