Update run_on_docker import
NUbots/NUbots pull request #379
Opened 2021-02-25 10:22 UTC by Y0sh1dk

Fix `run_on_docker` import to reflect changes in #376

2021-02-25 13:27 UTC, TrentHouliston approved these changes

2021-02-25 13:29 UTC, TrentHouliston requested changes
Actually, this might be a good time to take advantage of the new features of run_on_docker.
Since you should only really be running the unit tests on the `generic` image, changing your `@run_on_docker` annotations to `@run_on_docker(image="nubots:generic")` might be a good idea

2021-02-26 11:07 UTC, Y0sh1dk commented
Not sure if specifying image is necessary for the `register(command)` command, however I added it there too.

2021-02-26 23:01 UTC, TrentHouliston approved these changes

2021-02-26 23:35 UTC, merged