Add systemd units files and instructions for docker cleaning
NUbots/NUbots pull request #407
Opened 2021-03-27 00:36 UTC by Bidski

2021-03-27 01:34 UTC, KipHamiltons reviewed
I think we should add stuff to set this up to the NUbook guide to set up a buildkite agent, and to the script which does that automatically

2021-04-10 06:31 UTC, KipHamiltons requested changes

2021-04-10 06:31 UTC, KipHamiltons commented on doc/BuildKiteDockerClean/docker_clean.sh
> +#!/bin/bash
this also presupposes bash

2021-11-17 08:26 UTC, KipHamiltons commented
This is _kind of_ redundant now we have GHA.. Not sure if it will be useful if and when we use self-hosted runners though. Keen to hear thoughts @Bidski @Y0sh1dk

2022-07-29 04:44 UTC, CMurtagh-LGTM commented
We have moved to github actions, I'm assuming this in now irrelevant.

2022-07-29 04:44 UTC, closed without merging