Upgrades the DataLogging module to write an index as it writes the log
NUbots/NUbots pull request #419
Opened 2021-04-12 04:58 UTC by TrentHouliston

Depends on #414 as it uses the message reflection code

2021-04-12 06:52 UTC, CMurtagh-LGTM requested changes

2021-04-12 06:52 UTC, CMurtagh-LGTM commented on module/support/logging/DataLogging/src/DataLogging.cpp
> +#include "utility/nbs/Index.hpp"
NUbots does not have this :P.

2021-04-13 01:09 UTC, TrentHouliston commented on module/support/logging/DataLogging/src/DataLogging.cpp
> +#include "utility/nbs/Index.hpp"
Seems like an oversight...

2021-04-13 03:13 UTC, CMurtagh-LGTM approved these changes
¯\_(ツ)_/¯

2021-04-13 05:42 UTC, merged