Adds NUsight's dependencies to the dockerfile
NUbots/NUbots pull request #447
Opened 2021-04-30 07:36 UTC by KipHamiltons

2021-04-30 11:26 UTC, Y0sh1dk commented
This fixes the issue with `./b format` not formatting NUsight files. However with the depenedencies, `./b format` changes a few NUsight files, will this cause issues with the CI pipeline as it currently passes without these changes?
![image](https://user-images.githubusercontent.com/47013245/116688606-49ccaa80-a9fa-11eb-9cf2-94fcc5182862.png)

2021-04-30 22:51 UTC, JosephusPaye requested changes

2021-04-30 22:51 UTC, JosephusPaye commented on docker/Dockerfile
> +    nodejs \
Use the LTS ([fermium is v14](https://wiki.archlinux.org/index.php/Node.js_#Installation), the current LTS):

```suggestion
    nodejs-lts-fermium \
```

2021-05-20 07:23 UTC, JosephusPaye approved these changes
LGTM

2021-05-20 07:28 UTC, merged