Modify getup to use raw sensors average
NUbots/NUbots pull request #470
Opened 2021-05-22 22:49 UTC by tayloryoung6396

2021-05-23 04:16 UTC, Bidski requested changes
Format things too

2021-05-23 04:16 UTC, Bidski commented on module/behaviour/skills/Getup/src/Getup.cpp
> +                    }
```suggestion
                    // If we are on our side (== 0.0) then we want to execute the rollover
                    isFront = (M_PI_2 - std::acos(EigenVector3d::UnitX().dot(acc_reading)) >= 0.0);
```

2021-05-23 04:16 UTC, Bidski commented on module/behaviour/skills/Getup/src/Getup.cpp
> +            [this](const std::list<std::shared_ptr<const RawSensors>>& sensors) {
```suggestion
        on<Trigger<ExecuteGetup>>().then(
            "Execute Getup",
            [this]() {
```

2021-05-23 04:19 UTC, tayloryoung6396 commented on module/behaviour/skills/Getup/src/Getup.cpp
> +            [this](const std::list<std::shared_ptr<const RawSensors>>& sensors) {
I don't have clang.. :P

2021-05-23 04:36 UTC, Bidski requested changes

2021-05-23 04:36 UTC, Bidski commented on module/behaviour/skills/Getup/src/Getup.cpp
> +                acc_reading.normalize();
The more I think about it, the more I feel like we actually need to do this
```suggestion
                acc_reading = (acc_reading / double(sensors.size())).normalized();
```

2021-05-23 04:36 UTC, Bidski commented on module/behaviour/skills/Getup/src/Getup.cpp
> +                    }
```suggestion
                    // If we are on our side, treat it as being on our front, hopefully the rollover will help matters
                    isFront = (M_PI_2 - std::acos(EigenVector3d::UnitX().dot(acc_reading)) >= 0.0);
```

2021-05-23 05:06 UTC, Bidski submitted a review, later dismissed
Looks ok

2021-05-23 07:07 UTC, tayloryoung6396 commented
Works on the robot, someone should test it in webots

2021-05-24 11:56 UTC, Bidski reviewed
LGTM. Pending sim testing

2021-06-01 06:28 UTC, ysims commented
Does appear to work in webots.

2021-06-01 06:32 UTC, tayloryoung6396 commented
> Does appear to work in webots.

You could have approved it..

2021-06-01 06:37 UTC, ysims approved these changes
Seems good enough.

2021-06-01 06:41 UTC, merged