Add bh
NUbots/NUbots pull request #608
Opened 2021-06-25 20:44 UTC by TheCoolKidsTable

2021-06-25 20:47 UTC, tayloryoung6396 reviewed
LGTM

2021-06-25 20:47 UTC, tayloryoung6396 commented on module/vision/BallDetector/src/BallDetector.cpp
> +                        // log(rBCc.x(),rBCc.y(),rBCc.z());
WTF

2021-06-25 20:47 UTC, tayloryoung6396 commented on module/input/GameController/data/config/GameController.yaml
> +udp_filter_address: "10.1.0.103" # If set, will only accept GameController packets from this IP address
Remove this shit!

2021-06-25 20:47 UTC, tayloryoung6396 commented on module/behaviour/strategy/SoccerStrategy/src/SoccerStrategy.cpp
> +    // }
This should go later...

2021-06-25 21:11 UTC, KipHamiltons reviewed
yaaaay 7 am review yaaaay :tada: :taco: :shrimp: :fried_egg:

2021-06-25 21:11 UTC, KipHamiltons commented on module/behaviour/strategy/SoccerStrategy/src/SoccerStrategy.cpp
> +        // find({FieldTarget(FieldTarget::Target::SELF)});
seems strange? also, commented code

2021-06-25 21:11 UTC, KipHamiltons commented on module/behaviour/strategy/SoccerStrategy/src/SoccerStrategy.cpp
> +        if (NUClear::clock::now() - startedWalkingToReadyAt < std::chrono::milliseconds(17*1000)) {
magic number. any rationale behind it?

2021-06-25 21:11 UTC, KipHamiltons commented on module/behaviour/strategy/SoccerStrategy/src/SoccerStrategy.cpp
> +        // find({FieldTarget(FieldTarget::Target::SELF)});
wondering the general idea behind commenting all of these

2021-06-25 21:11 UTC, KipHamiltons commented on module/behaviour/strategy/SoccerStrategy/src/SoccerStrategy.cpp
> +        // find({FieldTarget(FieldTarget::Target::BALL)});
If you're in normal set, shouldn't you be finding yourself? - someone cool, probably

2021-06-25 21:11 UTC, KipHamiltons commented on module/behaviour/strategy/SoccerStrategy/src/SoccerStrategy.cpp
> +            find({FieldTarget(FieldTarget::Target::BALL)});
shouldn't you localise yourself, when you're penalised? you can teleport to the other side of the field, so localising self might be important?? @tayloryoung6396  thoughts?

2021-06-25 21:11 UTC, KipHamiltons commented on module/behaviour/strategy/SoccerStrategy/src/SoccerStrategy.cpp
> +            return;
don't need it

2021-06-25 21:11 UTC, KipHamiltons commented on module/behaviour/strategy/SoccerStrategy/src/SoccerStrategy.cpp
> +        if (NUClear::clock::now() - ballLastMeasured < cfg_.ball_last_seen_max_time && std::abs(rBTt.x()) < 10 && std::abs(rBTt.y()) < 10 && std::abs(rBTt.z()) < 10) {
why 10. ideal world adds a comment

2021-06-25 21:11 UTC, KipHamiltons commented on module/behaviour/strategy/SoccerStrategy/src/SoccerStrategy.cpp
> +        // find({FieldTarget(FieldTarget::Target::SELF)});
these are kinda whack. these commented out bits. idk :shrimp:

2021-06-25 21:11 UTC, KipHamiltons commented on module/vision/BallDetector/src/BallDetector.cpp
> +                        // log(rBCc.x(),rBCc.y(),rBCc.z());
"we do this somewhere else"

2021-06-25 21:19 UTC, KipHamiltons approved these changes
This is disgustingly hacky. yikes. But, I am taking you on your word that it's an improvement on the stuff in master currently. If that's true, then ship it baby lets get this merged yewwww.
I can't see anything that is obviously (unintentionally) broken (localisation is intentionally broken, so that doesn't count lol). sure.

2021-06-25 21:24 UTC, Bidski commented on module/behaviour/planning/SimpleWalkPathPlanner/src/SimpleWalkPathPlanner.cpp
> +                    emit(std::make_unique<ActionPriorities>(ActionPriorities{subsumptionId, {40, 11}}));
Changes priorities for each item in the limb set

2021-06-25 21:24 UTC, Bidski commented on module/behaviour/planning/SimpleWalkPathPlanner/src/SimpleWalkPathPlanner.cpp
> +                    emit(std::make_unique<ActionPriorities>(ActionPriorities{subsumptionId, {40, 11}}));
The magic is some relative importance on how much you want those limbs

2021-06-25 22:15 UTC, Bidski requested changes

2021-06-25 22:15 UTC, Bidski commented on module/platform/Webots/src/Webots.cpp
> +            image->timestamp = NUClear::clock::now();
Setting it to `NUClear::clock::now()` should actually be preferred to what we had before anyway
```suggestion
            image->timestamp = NUClear::clock::now();
```

2021-07-14 09:57 UTC, KipHamiltons commented
What's happening with this PR @TheCoolKidsTable? Does it have stuff you want to keep/merge?

2021-07-15 04:02 UTC, closed without merging