Adds flags to enable or disable a set of roles, doing the opposite to the other roles
NUbots/NUbots pull request #652
Opened 2021-07-22 10:45 UTC by KipHamiltons

This PR resolves #651 - basically I am tired of running `./b configure -i` and spamming space to disable all roles except one.
The PR does that by using the role selecting capability @JosephusPaye wrote for `./b webots` - I moved that function into `b` itself.

This PR might be contentious because I moved the function into `b`. I am willing to budge on that of course @TrentHouliston; it just seemed like the most reasonable solution for a `b` tool utility function.

### Reviewers, note

To test, it's `./b configure -r <roles> # enables <roles>` or `./b configure -R <roles> # disables <roles>`, where `<roles>` is a colon-separated list of role names. You can all do `./b configure -r all` to enable all roles.

2021-07-23 00:22 UTC, TrentHouliston commented
I am still of the opinion this should be done in CMake and you do `./b configure -DSOMETHINGHERE=ROLE_X

2021-07-24 03:23 UTC, KipHamiltons commented
@TrentHouliston what's the advantage to keeping that within cmake as opposed to in a `b` script?

2021-07-27 02:35 UTC, Bidski requested changes

2021-07-27 02:35 UTC, Bidski commented on nuclear/b.py
> +    return role_flags
Maybe something like this?

```suggestion
def get_cmake_role_flags(roles, disable_roles=False):
    """
    @brief Utility function to get list of CMake flags corresponding to the roles passed in.
    If disable_roles == True, then those roles are the only ones not enabled in the
    resulting flag list
    @param roles The roles to enable (or disable, if disable_roles == True)
    @param disable_roles Indicates whether the roles passed in should be enabled or disabled
    """

    roles_dir = os.path.join(project_dir, "roles")
    roles_glob = os.path.join(roles_dir, "*.role")

    available_roles = set([Path(role_path).stem for role_path in glob.glob(roles_glob)])

    # Ensure that all the roles requested are available
    failure = False
    for role in roles:
        if role not in available_roles:
            print(f"role '{role}' not found")
            failure = True
    if failure:
        sys.exit(1)
        
    # Deal with the roles that were passed in first
    toggle = "OFF" if disable_roles else "ON"
    roles = set(roles)
    role_flags = [f"-DROLE_{role}={toggle}" for role in roles]

    # Now deal with the roles that weren't passed in
    toggle = "ON" if disable_roles else "OFF"
    available_roles = available_roles - roles
    role_flags.extend([f"-DROLE_{role}={toggle}" for role in available_roles])

    return role_flags
```

2021-07-27 02:35 UTC, Bidski commented on tools/configure.py
> +
Add a command to list all known roles to make it easier to list enabled/disabled roles
```suggestion
    command.add_argument("-l", "--list-roles", action="store_true", dest="list_roles", default=False, help="List all known roles in the system")
```

2021-07-27 02:35 UTC, Bidski commented on tools/configure.py
> +        cprint(str(disabled_roles), color="green", attrs=["bold"])
`from termcolor import colored`
```suggestion
        desc_str = colored("Disabling all roles except these:", color="red", attrs=["bold"])
        roles_str = colored(", ".join([role for role in disabled_roles]), color="green", attrs=["bold"])
        print(f"{desc_str} {roles_str}")
```

2021-07-27 04:37 UTC, TrentHouliston commented
> @TrentHouliston what's the advantage to keeping that within cmake as opposed to in a `b` script?

Cohesion, so that the code that configures which roles to build is all in the same place, not split into two places

2023-08-13 00:01 UTC, ysims commented
Superceded by #1031

2023-08-13 00:01 UTC, closed without merging