Changes the leg IK functions to templates
NUbots/NUbots pull request #717
Opened 2021-09-18 22:28 UTC by ysims

^

2021-09-25 04:16 UTC, KipHamiltons commented on shared/utility/motion/InverseKinematics.hpp
> +        const Scalar lowerLeg    = std::acos(std::fmax(std::fmin(cosLowerLeg, 1), -1));
```suggestion
        const Scalar lowerLeg    = std::acos(std::max(std::min(cosLowerLeg, 1), -1));
```

2021-09-25 04:16 UTC, KipHamiltons commented on shared/utility/motion/InverseKinematics.hpp
> +                "moment. requested pose = \n",
```suggestion
                "the moment. requested pose = \n",
```

2021-09-25 04:22 UTC, ysims commented on module/motion/QuinticWalk/src/QuinticWalk.cpp
> +            calculateLegJoints<float>(kinematicsModel, Eigen::Affine3f(left_foot), Eigen::Affine3f(right_foot));
Yeah I was really confused by the error it was giving me like surrrrrrely you can figure that out, but nope.

2021-09-25 04:22 UTC, ysims commented on shared/utility/motion/InverseKinematics.hpp
> +        // TODO remove this. It was due to wrong convention use
I'll make an issue. I have no idea what it even is.

2021-09-25 10:08 UTC, KipHamiltons commented
Build broke, otherwise lgtm

2021-10-02 01:38 UTC, KipHamiltons requested changes

2021-10-02 01:38 UTC, KipHamiltons commented on shared/utility/motion/InverseKinematics.hpp
> +        const Eigen::Affine3f& rightTarget) {
Same for the `leftTarget`
```suggestion
        const Eigen::Transform<Scalar, 3, Eigen::Affine>& rightTarget) {
```

2021-10-02 04:43 UTC, KipHamiltons approved these changes
LGTM!!!

2021-10-02 04:44 UTC, merged