Obrien/kick script changes
NUbots/NUbots pull request #842
Opened 2022-06-11 11:15 UTC by TheCoolKidsTable

It seems an ExecuteKick message is being emitted when the kick script is registering action and since the current trigger in kick script will execute a kick regardless of if its kickCommand is valid, a kick is executed.

This PR adds check for valid limb id and type in kick command which fixes the kick script being executed when running `webots_keyboard`. 

@Bidski mentioned another method using a shared_ptr but I am not 100% on how to go about implementing this, maybe that is a better approach.

2022-06-11 11:19 UTC, Bidski requested changes
This method should be fine, just fix up your comments

2022-06-11 11:19 UTC, Bidski commented on module/behaviour/skills/KickScript/src/KickScript.cpp
> +            // Execute the penalty kick if the type is PENALTY
Copy-pasting is bad

2022-06-11 11:25 UTC, Bidski commented
Sorry @TheCoolKidsTable,  I should have been more explicit. That comment (along with the other one) says _what_ the code says. Comments should say _why_ the code does what it does, what does the code _mean_?

2022-06-12 07:00 UTC, ysims reviewed
It looks like you're not really using the subsumption system here? We shouldn't have to check if the robot is getting up or kicking currently if we use subsumption. It looks like it would break in some cases.

2022-06-13 05:38 UTC, BryceTuppurainen approved these changes
All the changes makes sense to me, can't see anything I'd critique here :+1: (That hasn't already been mentioned)

2022-06-14 23:31 UTC, closed without merging