Stop Configuration running multiple times with the same data during installation phase of the program
NUbots/NUbots pull request #850
Opened 2022-06-19 08:09 UTC by ysims

A possible way to fix the issue where multiple runs of the Configuration reactor occurs with the same data at the beginning of the program. 

I'm not sure if using the `NO_OP` is a bit dodgy, and it might be better to see if there's a way to modify `FileWatcher` to set a particular event type for this. 

But regardless there is still a problem with this. As far as I can tell, this should be okay, however it only works for the first module where multiple config exist. I've been testing with `webotsrobocup` and SensorFilter skips the extra config files (reaches the if statement and does not run the Configuration reactor). 
After this, VisualMesh loads and its offending config files also reach the `if` statement (therefore emitting `nullptr`) BUT the Configuration reactor is triggered again.

2022-06-19 08:40 UTC, Bidski commented
If checking for `NO_OP` is the correct option then I would do it [here](https://github.com/NUbots/NUbots/blob/main/module/extension/FileWatcher/src/FileWatcher.cpp#L46-L64)  and dont call `reactor.powerplant.submit(std::move(task));` (not sure what else you need to not to do, @TrentHouliston )

2022-06-19 10:39 UTC, ysims commented
Yeah. My understanding was the FileWatcher is a generic module for seeing file events. While Configuration is the one that doesn't want to see repeat config at the beginning. But I can't really see how else to do it in Configuration if this `nullptr` thing won't work.

2022-06-19 22:48 UTC, Bidski commented
You are quite correct, `FileWatcher` is its own module and it shouldn't know anything about the inner workings of the `Configuration` extension, so doing the checks in `FileWatcher` is not a smart idea.

What you sort of want to do is send a list of files to `FileWatcher` and have it notify you if any one of those files gets modified. However, `libuv` only lets you trigger an event for 1 file at a time, so I feel like making this work would be complicated

2022-06-20 07:40 UTC, CMurtagh-LGTM commented
Why are we changing the `get` method, shouldn't we be adding overriding `precondition`?
```
bool precondition(threading::Reaction& reaction){
::extension::FileWatch watch = DSLProxy<::extension::FileWatch>::get<DSL>(r);
...
    if (watch.events == ::extension::FileWatch::Event::NO_OP && ((component == hostname) ||
        (component == binaryName) || (component == platform))) {
        return false;
    }
...
}
```

2022-06-20 07:48 UTC, CMurtagh-LGTM commented
As I remember precondition stops the reaction on false and proceeds on a true return.

2022-06-20 08:46 UTC, ysims commented
I'm not familiar with these different functions, but I'll have a go with the suggestion, ty @CMurtagh-LGTM

2022-06-21 06:58 UTC, CMurtagh-LGTM requested changes
Looking good
However I don't like how they are now out of order; `precondition` should go above `get` and below `bind`.

2022-06-21 06:58 UTC, CMurtagh-LGTM commented on shared/extension/Configuration.hpp
> +            /// @return True if the file is valid, otherwise false.
```suggestion
            /// @return False is the reaction is not to be run, otherwise true
```
Can return true or false if file is a `NO_OP`.

2022-06-22 02:34 UTC, CMurtagh-LGTM submitted a review, later dismissed
LGTM

2022-06-22 07:22 UTC, ysims commented
Added some stuff for robustnuss, it won't check hostname, platform name or role name on stuff in the path before "config" (and including) and the actualy yaml file name.

2022-06-23 04:04 UTC, CMurtagh-LGTM approved these changes

2022-06-23 04:44 UTC, merged