Disable PGP rather than trying to use a separate keychain
NUbots/NUbots pull request #896
Opened 2022-07-12 12:28 UTC by TrentHouliston

This changes how PGP is handled so that rather than trying to update to the latest keychain before installing (which can fail sometimes) it just blindly installs packages without checking them.

Since we're date locked sometimes keys will expire and it won't install because of PGP errors. This gets rid of those errors by not checking.

The downside is there is an infinitesimal chance that if someone were able to compromise your package download they could add something malicious.

### Pre-PR Checklist:

Have you
- [ ] Updated NUbook if necessary (add link to NUbook PR here)
- [ ] Added/updated tests for your changes, including regression tests for bug fixes
- [ ] Updated relevant module READMEs
- [ ] Added/modified [documentation directives](https://nubook.nubots.net/guides/general/code-conventions#documentation) in relevant code
- [ ] Added a descriptive title and relevant labels to the PR

2022-07-13 01:23 UTC, Bidski requested changes

2022-07-13 01:23 UTC, Bidski commented on docker/etc/pacman.conf
> +# Trust anything so we don't get signature errors for old packages while date locked
```suggestion
# Trust everything so we don't get signature errors for old packages while date locked
```

2022-07-13 03:00 UTC, miikyla approved these changes
Looks good

2022-07-23 13:26 UTC, Crafty15 approved these changes
LGTM

2022-07-23 13:54 UTC, merged