Added MainThread to 'ON' statements
NUbots/NUbots pull request #921
Opened 2022-08-06 04:08 UTC by PiiDish

Main Thread - <on.....

2022-08-06 06:01 UTC, Bidski requested changes

2022-08-06 06:01 UTC, Bidski commented on module/motion/QuinticWalk/src/QuinticWalk.cpp
> +        on<Configuration, MainThread>("QuinticWalk.yaml").then([this](const Configuration& cfg) {
Adding `MainThread` to `on<Configuration>` should be a pointless and unneeded operation, pretty sure you don't need it for `on<Startup>` either

2022-08-06 07:23 UTC, TrentHouliston reviewed
You should only need this on the reactions that are time sensitive. So the update on the walk, and the hardware io ones that work with sensors. Maybe subsumption too. Basically the critical path. The rest of these will do nothing except make things slower that are important. 

If you overload the main thread with too much stuff you'll be back to the exact same problem as you started with

2022-08-30 23:00 UTC, Bidski approved these changes

2023-06-20 04:40 UTC, ysims commented
Not really needed atm, not having problems with walk. Also this is out of date in that we don't use this module anymore.

2023-06-20 04:40 UTC, closed without merging