Update the formatting system
NUbots/NUbots pull request #979
Opened 2022-11-11 09:03 UTC by TrentHouliston

This PR updates the formatting system so that both the check in CI and the formatting is done using the same python file.

It also enables formatting for more file types and fixes an issue where NUsight2 wasn't actually getting formatted by prettier.

Currently I haven't applied any of the formatting as now is the time if anyone wants to make any formatting rule changes.

2022-11-11 09:11 UTC, Bidski requested changes

2022-11-11 09:11 UTC, Bidski commented on .github/workflows/nubots.yaml
>        - name: Check clang-format
```suggestion
       - name: Check formatting 
```

2022-11-11 09:14 UTC, Bidski reviewed
Consider me approving but not approving to allow people to argue about formatting

2022-11-18 22:29 UTC, CMurtagh-LGTM submitted a review, later dismissed

2022-11-18 22:31 UTC, CMurtagh-LGTM commented
I'm not the biggest fan of removing the ability to skip files that weren't changed, but I don't think I've personally needed it in a while, so we'll see how this goes.

2022-11-19 05:12 UTC, LachlanCourt approved these changes

2022-11-19 05:32 UTC, merged