Add a Script extension that works with Director
NUbots/NUbots pull request #992
Opened 2022-12-08 20:32 UTC by ysims

Allows us to do

```cpp
emit<Script>(std::make_unique<LimbsSequence>(), "KickRight.yaml");
```

Then that'll load the script and emit a LimbsSequence for that script.

Future work: cache scripts

2022-12-08 22:34 UTC, CMurtagh-LGTM requested changes
Please don't call it `NewScript`.

2022-12-08 22:34 UTC, CMurtagh-LGTM commented on shared/extension/NewScript.hpp
> +            }
```suggestion
```
You use initialiser lists.

2022-12-08 22:34 UTC, CMurtagh-LGTM commented on shared/extension/NewScript.hpp
> +        static YAML::Node load_script(const std::string& script) {
```suggestion
        static YAML::Node load(const std::string& script) {
```
Doubling up on the name script, `Script::load_script` vs `Script::load`.

2022-12-08 22:34 UTC, CMurtagh-LGTM commented on shared/extension/NewScript.hpp
> +            : duration(dur), targets(std::move(targets)) {}
```suggestion
```
There's no point here as well.

2022-12-08 22:34 UTC, CMurtagh-LGTM commented on shared/extension/NewScript.hpp
> +        NUClear::clock::duration duration;
```suggestion
        NUClear::clock::duration duration{};
```
Initialise it, if you delete the constructor.

2022-12-08 22:55 UTC, ysims commented
> Please don't call it `NewScript`.

Do you have a suggestion? :P maybe we need a director branch already after all :weary:

2022-12-15 00:21 UTC, TrentHouliston reviewed
One minor point

2022-12-15 00:21 UTC, TrentHouliston commented on shared/extension/behaviour/Script.hpp
> +        static inline std::string getPlatform(const std::string& hostname) {
```suggestion
        static inline std::string get_platform(const std::string& hostname) {
```

2022-12-15 00:29 UTC, TrentHouliston approved these changes

2022-12-15 01:56 UTC, merged

2022-12-15 02:00 UTC, CMurtagh-LGTM commented
> because he's busy teaching johanne maths
:stuck_out_tongue: